# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- develop

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- checkout: self
  persistCredentials: true

- task: gitversion/setup@0
  displayName: 'Install GitTools'
  inputs:
    versionSpec: '5.3.x'
- task: gitversion/execute@0
  displayName: 'Calculate SemVer'
- script: echo current version is $(GitVersion.SemVer)
  displayName: 'Display calculated version'
